#python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing1"
#python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing2"
#python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing3"
python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing4"
python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing5"
python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing6"
python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing7"
python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing8"
python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing9"
python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing10"
python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing11"
python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing12"
python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing13"
python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing14"
python reproduce_critiquing.py --data_dir "data/beer/" --load_path "critiquing_hyperparameters/beer/hyper_parameters.csv" --num_users_sampled 500 --save_path "beer_fmap/beer_Critiquing15"

