#python reproduce_general_results.py --data_dir data/beer/ --tuning_result_path beer_rating_tuning --save_path beer_rating_final/beer_final_result1.csv
#python reproduce_general_results.py --data_dir data/beer/ --tuning_result_path beer_rating_tuning --save_path beer_rating_final/beer_final_result2.csv
#python reproduce_general_results.py --data_dir data/beer/ --tuning_result_path beer_rating_tuning --save_path beer_rating_final/beer_final_result3.csv
#python reproduce_general_results.py --data_dir data/beer/ --tuning_result_path beer_rating_tuning --save_path beer_rating_final/beer_final_result4.csv
#python reproduce_general_results.py --data_dir data/beer/ --tuning_result_path beer_rating_tuning --save_path beer_rating_final/beer_final_result5.csv
python reproduce_general_results.py --data_dir data/CDsVinyl/ --tuning_result_path CDsVinyl_rating_tuning --save_path CDsVinyl_rating_final/CDsVinyl_final_result1.csv
python reproduce_general_results.py --data_dir data/CDsVinyl/ --tuning_result_path CDsVinyl_rating_tuning --save_path CDsVinyl_rating_final/CDsVinyl_final_result2.csv
python reproduce_general_results.py --data_dir data/CDsVinyl/ --tuning_result_path CDsVinyl_rating_tuning --save_path CDsVinyl_rating_final/CDsVinyl_final_result3.csv
python reproduce_general_results.py --data_dir data/CDsVinyl/ --tuning_result_path CDsVinyl_rating_tuning --save_path CDsVinyl_rating_final/CDsVinyl_final_result4.csv
python reproduce_general_results.py --data_dir data/CDsVinyl/ --tuning_result_path CDsVinyl_rating_tuning --save_path CDsVinyl_rating_final/CDsVinyl_final_result5.csv
