parameters:
    models: E-CDE-VAE
    epoch: [300, 600]
    beta: [0.0001, 0.001, 0.01]
    lambda_l2: [0.0001, 0.001, 0.01]
    lambda_keyphrase_latent: [0.0001, 0.001, 0.01, 0.1, 1.0]
    lambda_rating: [1.0]
    rank: [100, 200]
    corruption: [0.2, 0.3, 0.4, 0.5]
    optimizer: [Adam]
    learning_rate: [0.0001, 0.0005, 0.001]
    topK: [5, 10, 15, 20, 50]
    metric: [R-Precision, NDCG, Precision, Recall, MAP]
